version: '3.7'

services:
  backend:
    volumes:
      - ./backend:/app
    env_file:
      .env

    build:
      context: ./backend
    ports:
      - "8000:8000"



  frontend:   
    env_file:
      .env 

    build:  
      context: ./frontend

    ports: 
      - "3000:3000"